---
 - name: Playbook to copy files
   become: true
   hosts: all
   tasks:
     - name: Copy file with owner permissions
       copy:
        src: /home/ubuntu/copy/testing_copy
        dest: /home/ubuntu
        owner: root
        group: root
        mode: '0644'

